# Generated by Django 2.0.7 on 2020-03-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20200306_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
