# Generated by Django 2.0.7 on 2020-03-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200306_1530'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseorg',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
